"""Configuration of pytest: fixtures and additional features"""

import os
import re
import sys
from pathlib import Path
from shutil import rmtree
from typing import Generator, Union

import pytest
import matplotlib.pyplot as plt


PathType = Union[str, os.PathLike[str]]
TEST_DIR = Path(__file__).parent

sys.path.insert(0, str(TEST_DIR / "utils"))
pytest_plugins = ["utils.proxies"]  # Load fixtures from utils/proxies.py


def pytest_addoption(parser: pytest.Parser) -> None:
    """Register CLI option to manage code generation."""
    help_no_codegen = (
        "Skip (when possible) running the Scade One code generation jobs."
        "  This includes generation of Python Wrapper: it is faster when proxies already built."
    )
    parser.addoption("--no-codegen", action="store_true", help=help_no_codegen)


def _get_plot_dir(node_id: str, clean_dir: bool = False) -> Path:
    """Get the directory where plots for the given test nodeid are stored."""

    # The simplest way to be able to save multiple plots from the same test,
    # is to have a dedicated directory per test.
    # For the directory name, we need to create a sanitized file name from node id
    file_stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", node_id)

    plot_dir = TEST_DIR / "plots" / file_stem
    if clean_dir and plot_dir.exists():
        rmtree(plot_dir)

    return plot_dir


@pytest.fixture(autouse=True)
def _manage_plt_show(request: pytest.FixtureRequest) -> Generator[None, None, None]:
    """Automatically used Fixture that intercepts calls to matplotlib.pyplot.show.

    * When a test is run alone, the plots are shown interactively on the screen.
    * When several tests are run, the plots generated by `plt.show` are saved to a file.
    """
    is_test_run_alone = getattr(request.session, "testscollected", 0) == 1
    if is_test_run_alone:
        # Nothing to do, allow normal behavior
        yield
        return

    # Replace plt.show with a saver function
    # ... As we are in a fixture for a Test Case, we can create an empty directory
    orig_show = plt.show
    plot_dir = _get_plot_dir(request.node.nodeid, clean_dir=True)

    def _save_plot(*args, **kwargs):
        """Save the current plot to a file instead of showing it on screen."""
        # We need to have the most robust way of saving the current figure
        # ... and if all fails, we shall ensure that the test is not broken
        plot_dir.mkdir(exist_ok=True, parents=True)
        counter = len(list(plot_dir.glob("*.png"))) + 1
        path = plot_dir / f"plot_{counter:02d}.png"
        try:
            plt.savefig(str(path))
        except Exception:
            try:
                fig = plt.gcf()
                fig.savefig(str(path))
            except Exception:
                pass  # All failed 😭
        finally:
            try:
                plt.close("all")
            except Exception:
                pass

    # We can now temporarily replace plt.show and revert at the end
    plt.show = _save_plot
    yield
    plt.show = orig_show


def pytest_html_results_table_html(report, data: list[str]):
    """Add plot images to HTML report when they exist for the test."""
    if not hasattr(report, "nodeid"):
        return

    plot_dir = _get_plot_dir(report.nodeid)
    if plot_dir.exists():
        plot_files = sorted(plot_dir.glob("*.png"))
        # Add a new cell with the images
        plot_html = "<div>"
        for plot_file in plot_files:
            rel_path = plot_file.relative_to(TEST_DIR.parent)
            plot_html += (
                f'<img src="{rel_path}" style="max-width:20000px; margin:5px;" />'
            )
        plot_html += "</div>"

        data.insert(1, f"<td>{plot_html}</td>")
